services:
  redis:
    image: redis:alpine
    restart: on-failure
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - $REDISDATA
      - redis_data:/data
    command:
      - redis-server /usr/local/etc/redis/redis_logs.conf

volumes:
  redis_data: