services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate && 
            python manage.py runserver 0.0.0.0:8000"
    restart: on-failure
    depends_on:
      - redis


  redis:
    image: redis:alpine
    restart: on-failure
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - $REDISDATA
      - redis_data:/data
    command:
      - redis-server
      - /usr/local/etc/redis/redis_logs.conf

#  celery:
#    build:
#      context: .
#    command: celery -A CityLibraryServiceAPI worker --loglevel=INFO
#    restart: on-failure
#    env_file:
#      - .env
#    depends_on:
#      - redis
#
#  flower:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "5555:5555"
#    command: celery -A CityLibraryServiceAPI flower --address=0.0.0.0
#    restart: on-failure
#    env_file:
#      - .env
#    depends_on:
#      - celery

volumes:
  redis_data: