# Generated by Django 5.1 on 2024-10-03 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0002_rename_borrowing_borrowingmodel"),
        ("payment", "0002_alter_paymentmodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmodel",
            name="borrow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="borrowing.borrowingmodel",
            ),
        ),
    ]
