# Generated by Django 5.1 on 2024-08-15 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="daily_fee",
            field=models.DecimalField(
                db_comment="Book daily fee",
                decimal_places=2,
                default=0.0,
                help_text="Book daily fee",
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
