# Generated by Django 5.1 on 2024-08-15 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0002_alter_book_daily_fee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borrow_date",
                    models.DateField(
                        auto_now_add=True,
                        db_comment="Borrowing date of the book",
                        help_text="Borrowing date of the book",
                    ),
                ),
                (
                    "expected_return_date",
                    models.DateField(
                        db_comment="Expected return date of the book",
                        help_text="Expected return date of the book",
                    ),
                ),
                (
                    "actual_return_date",
                    models.DateField(
                        blank=True,
                        db_comment="Actual return date of the book",
                        help_text="Actual return date of the book",
                        null=True,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        db_comment="Book which the user is borrowed",
                        help_text="Book",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="User who borrowed the book",
                        help_text="User",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-expected_return_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("book", "user"), name="unique_borrowing"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "expected_return_date__gte",
                                models.F("borrow_date"),
                            )
                        ),
                        name="expected_return_date_check",
                    ),
                ],
            },
        ),
    ]
