# Generated by Django 5.1 on 2024-10-03 05:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_daily_fee"),
        ("borrowing", "0001_initial"),
        ("payment", "0002_alter_paymentmodel_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Borrowing",
            new_name="BorrowingModel",
        ),
    ]
