name: Flake8 Lint for Request

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run flake8
      run: flake8 .

    - name: Run tests
      run: python manage.py test
